# Generated by Django 3.2.1 on 2021-06-01 21:27

from django.db import migrations
import stdimage.models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='photo',
            field=stdimage.models.StdImageField(null=True, upload_to=users.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
