# Generated by Django 3.2.1 on 2021-05-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_profile'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='cd_cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cidade'),
        ),
    ]
