# Generated by Django 3.2.1 on 2021-06-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210605_0037'),
        ('users', '0002_alter_newuser_cd_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='cd_publicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publicacao'),
        ),
    ]
