# Generated by Django 3.2.1 on 2021-06-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210605_0037'),
        ('users', '0003_newuser_cd_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='cd_publicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.publicacao'),
        ),
    ]
