# Generated by Django 3.2.1 on 2021-05-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_remove_newuser_cd_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='cd_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.regional'),
        ),
    ]
