# Generated by Django 3.2.1 on 2021-05-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_profile'),
        ('users', '0004_alter_newuser_cd_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='cd_cidade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.cidade'),
        ),
    ]
