# Generated by Django 3.2.1 on 2021-06-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_cd_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='cd_publicacao',
        ),
    ]
