# Generated by Django 3.2.1 on 2021-06-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210605_0142'),
        ('users', '0005_remove_newuser_cd_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='cd_publicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.publicacao'),
        ),
    ]
