# Generated by Django 3.2.1 on 2021-05-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cricao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario_criacao', models.CharField(max_length=100, verbose_name='Usuário Criação')),
                ('nome_atividade', models.CharField(max_length=100, verbose_name='Nome Atividade')),
                ('descricao_atividade', models.TextField(max_length=200, verbose_name='Descrição Atividade')),
            ],
            options={
                'verbose_name': 'Atividades',
            },
        ),
    ]
