# Generated by Django 3.2.1 on 2021-06-02 12:53

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('localizacao', models.FloatField(max_length=10000, verbose_name='Localização')),
                ('data_atividade', models.DateField(auto_now_add=True, verbose_name='Data Atividade')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao_atividade', models.CharField(max_length=100, verbose_name='Tipo Atividade')),
                ('pontos', models.IntegerField(blank=True, null=True, verbose_name='Pontuação')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Atividade',
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_regional', models.CharField(max_length=100, verbose_name='Nome regional')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regional',
                'verbose_name_plural': 'Regionais',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_dado', models.CharField(max_length=100, verbose_name='Pontuação')),
                ('nome_tabela', models.CharField(max_length=100, verbose_name='Nome tabela')),
                ('nome_campo', models.CharField(max_length=100, verbose_name='Nome campo')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranking',
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_premio', models.CharField(max_length=100, verbose_name='Nome prêmio')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('midia', models.ImageField(null=True, upload_to=core.models.get_file_path)),
                ('vigencia', models.DateTimeField(default=datetime.datetime.now)),
                ('data_premiacao', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('midia', models.ImageField(null=True, upload_to=core.models.get_file_path)),
                ('descricao_midia', models.CharField(default='NULL', max_length=500, verbose_name='Descrição')),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mídia',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('comentario', models.TextField(max_length=500, verbose_name='Comentário')),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('cd_tipo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoatividade')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
