# Generated by Django 3.2.1 on 2021-06-02 02:37

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models

from dbview.helpers import CreateView

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_newuser_photo'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interacao',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='midia',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premio',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ranking',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regional',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoatividade',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='midia',
            name='midia',
            field=stdimage.models.StdImageField(null=True, upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='midia',
            field=stdimage.models.StdImageField(null=True, upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        CreateView(
            name='ViewPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('nome_regional', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('midia', models.CharField(max_length=100)),
                ('publicacao', models.TextField(max_length=500)),
                ('localizacao', models.FloatField(max_length=10000)),
                ('data_publicacao', models.DateField()),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewPerfil',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.newuser')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('biografia', models.TextField(max_length=200)),
                ('foto', models.CharField(max_length=100)),
                ('nome_regional', models.CharField(max_length=100)),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('interacao', models.TextField(max_length=500)),
                ('id_interacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.interacao')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=500)),
                ('nome_regional', models.CharField(max_length=100)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
                ('id_usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_atividade', models.CharField(max_length=100)),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.atividade')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
