# Generated by Django 3.2.1 on 2021-06-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from dbview.helpers import CreateView

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        CreateView(
            name='ViewPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('nome_regional', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('midia', models.CharField(max_length=100)),
                ('publicacao', models.TextField(max_length=500)),
                ('localizacao', models.FloatField(max_length=10000)),
                ('data_publicacao', models.DateField()),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewPerfil',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.newuser')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('biografia', models.TextField(max_length=200)),
                ('foto', models.CharField(max_length=100)),
                ('nome_regional', models.CharField(max_length=100)),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('interacao', models.TextField(max_length=500)),
                ('id_interacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.interacao')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=500)),
                ('nome_regional', models.CharField(max_length=100)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
                ('id_usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        CreateView(
            name='ViewAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_atividade', models.CharField(max_length=100)),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.atividade')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
