# Generated by Django 3.2.1 on 2021-06-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewAtividades',
        ),
    ]
