# Generated by Django 3.2.1 on 2021-06-02 13:58

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('select \n            publi.id as id_publicacao,\n            atv.id as id_atividade,\n            tipoatv.descricao_atividade as descricao_atividade\n            from core_tipoatividade tipoatv\n            left join core_atividade atv on tipoatv.id = atv.cd_tipo_atividade_id\n            join core_publicacao publi on atv.cd_publicacao_id = publi.id \n            where publi.ativo = true\n            and tipoatv.ativo = true', 'viewAtividades', engine='django.db.backends.postgresql'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'viewAtividades', engine='django.db.backends.postgresql'),
            atomic=False,
        ),
    ]
