# Generated by Django 3.2.1 on 2021-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='postagemteste',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='regional',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='tipoatividade',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Alteracao'),
        ),
    ]
