# Generated by Django 3.2.1 on 2021-06-02 08:29

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_viewatividades_viewcomentario_viewinteracao_viewperfil_viewpublicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='midia',
            field=models.ImageField(null=True, upload_to=core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='premio',
            name='midia',
            field=models.ImageField(null=True, upload_to=core.models.get_file_path),
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_dado', models.CharField(max_length=100, verbose_name='Pontuação')),
                ('nome_tabela', models.CharField(max_length=100, verbose_name='Nome tabela')),
                ('nome_campo', models.CharField(max_length=100, verbose_name='Nome campo')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
    ]
