# Generated by Django 3.2.1 on 2021-05-24 23:09

from django.db import migrations, models
import django.db.models.deletion
from dbview.helpers import CreateView


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0002_auto_20210524_1235'),
    ]

    operations = [
        CreateView(
            name='ViewPerfil',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.newuser')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('biografia', models.TextField(max_length=200)),
                ('foto', models.CharField(max_length=100)),
                ('nome_regional', models.CharField(max_length=100)),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
