# Generated by Django 3.2.1 on 2021-05-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210505_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='dt_cricao',
            new_name='dt_criacao',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='dt_cricao',
            new_name='dt_criacao',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='dt_cricao',
            new_name='dt_criacao',
        ),
        migrations.RenameField(
            model_name='regional',
            old_name='dt_cricao',
            new_name='dt_criacao',
        ),
    ]
