# Generated by Django 3.2.1 on 2021-05-09 23:26

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210505_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estado',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regional',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_atividade', models.CharField(max_length=100, verbose_name='Nome Atividade')),
                ('pontos', models.IntegerField(blank=True, null=True, verbose_name='Pontuação')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nome Atividade',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('localizacao', models.FloatField(max_length=10000, verbose_name='Localização')),
                ('data_atividade', models.DateField(auto_now_add=True, verbose_name='Data Atividade')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('cd_tipo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoatividade')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('midia', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('flag_foto_perfil', models.BooleanField(default=True, verbose_name='Foto Perfil')),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mídia',
            },
        ),
        migrations.AddField(
            model_name='atividades',
            name='cd_publicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publicacao'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='cd_tipo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoatividade'),
        ),
    ]
