# Generated by Django 3.2.1 on 2021-05-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from dbview.helpers import CreateView


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_viewperfil'),
    ]

    operations = [
        CreateView(
            name='ViewComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=500)),
                ('nome_regional', models.CharField(max_length=100)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
                ('id_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacao')),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.regional')),
                ('id_usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
