# Generated by Django 3.2.1 on 2021-05-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210509_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoatividade',
            options={'verbose_name': 'Tipo Atividade'},
        ),
        migrations.RemoveField(
            model_name='tipoatividade',
            name='nome_atividade',
        ),
        migrations.AddField(
            model_name='tipoatividade',
            name='tipo_atividade',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Tipo Atividade'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='cd_tipo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoatividade'),
        ),
    ]
