# Generated by Django 3.2.1 on 2021-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210511_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='nome_atividade',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Nome Atividade'),
        ),
    ]
