# Generated by Django 3.2.1 on 2021-05-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_atividades_nome_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_atividade', models.CharField(default='NULL', max_length=100, verbose_name='Nome Atividade')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='cd_tipo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoatividade'),
        ),
        migrations.AlterField(
            model_name='tipoatividade',
            name='tipo_atividade',
            field=models.CharField(max_length=100, verbose_name='Tipo Atividade'),
        ),
        migrations.DeleteModel(
            name='Atividades',
        ),
        migrations.AddField(
            model_name='atividade',
            name='cd_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoatividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
