# Generated by Django 3.2.1 on 2021-05-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210511_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='descricao_midia',
            field=models.CharField(default='NULL', max_length=500, verbose_name='Descrição'),
        ),
    ]
