# Generated by Django 3.2.1 on 2021-06-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_atividade_cd_tipo_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='cd_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='core.publicacao'),
        ),
    ]
