# Generated by Django 3.2.1 on 2021-06-05 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_midia_cd_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='regional',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='regional',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='tipoatividade',
            name='dt_alteracao',
            field=models.DateTimeField(null=True, verbose_name='Data Alteracao'),
        ),
        migrations.AlterField(
            model_name='tipoatividade',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data início'),
        ),
    ]
