# Generated by Django 3.2.1 on 2021-05-13 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210512_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='data_premiacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='premio',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
