# Generated by Django 3.2.1 on 2021-06-05 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20210605_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
