# Generated by Django 3.2.1 on 2021-05-13 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20210512_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('interacao', models.BooleanField(default=False)),
                ('cd_publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacao')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
            },
        ),
    ]
