# Generated by Django 3.2.1 on 2021-06-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_publicacao_usuario_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cd_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='core.publicacao'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='cd_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacao', to='core.publicacao'),
        ),
    ]
