# Generated by Django 3.2.1 on 2021-05-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_interacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='flag_foto_perfil',
        ),
    ]
