# Generated by Django 3.2.1 on 2021-06-05 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210605_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
