# Generated by Django 3.2.1 on 2021-05-15 03:41

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_midia_flag_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('midia', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('cd_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
