# Generated by Django 3.2.1 on 2021-05-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210515_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
